sudo: false
install: true

email:
  recipients:
    - dev+travisloteria-crawlers@ueby.com
  on_success: change
  on_failure: always

addons:
  sonarcloud:
    organization: "algarves"
    token:
      secure: ${SONAR_TOKEN}

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'