# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Test

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'adopt' ]
        java: [ '8', '11', '13' ]
    name: Build project with Java ${{ matrix.Java }} (${{ matrix.distribution }})
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew --build-cache assemble

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        distribution: [ 'adopt' ]
        java: [ '11', '13' ]
    name: Testing with Java ${{ matrix.Java }} (${{ matrix.distribution }})
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Generate test report with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test integrationTest jacocoTestReport sonarqube -Dsonar.verbose=true
